name: Cypress Tests

on: 
  pull_request

jobs:
    cypress-run:
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - run: yarn install --frozen-lockfile
            - name: Cypress run
              uses: cypress-io/github-action@v3
              with:
                  build: yarn  run build
                  start: yarn  start