name: Cypress Tests

on: 
  pull_request

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: yarn install --frozen-lockfile
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: yarn dev
          start: yarn cypress open
          browser: chrome
