name: Cypress Tests

on: 
  pull_request

jjobs:
    cypress-test:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - run: yarn install --frozen-lockfile

            - name: run cypress tests in chrome
              uses: cypress-io/github-action@v5
              timeout-minutes: 10
              with:
                  browser: chrome
                  record: true
                  build: yarn build
                  start: yarn start
                  wait-on: 'http://localhost:3000'