name: Cypress Tests

on: 
  pull_request

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: yarn install --frozen-lockfile
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: yarn dev
          start: yarn cypress run --reporter mochawesome
          browser: chrome
      - name: Upload Mochawesome Report
        if: always() # Garante que o report será enviado mesmo se os testes falharem
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/mochareports

